.TH BIRCH 1
.SH NAME
birch \- an irc client written in pure bash.
.SH SYNOPSIS
.B birch
[\fB\-s\fR \fIhost\fR]
[\fB\-u\fR \fIuser\fR]
[\fB\-p\fR \fIpassword\fR]
[\fB\-c\fR \fIchannel\fR]

.SH DESCRIPTION
.B birch is a minimal irc client written in pure bash.

.SH OPTIONS
.TP
.BR \-s\ host
Server to connect to (required).
.TP
.BR \-u\ user
Username to use (required).
.TP
.BR \-p\ password
Password to use.
.TP
.BR \-c\ channel
Channel to join.
.TP
.BR \-h
Show usage and exit.
.TP
.BR \-v
Show version and exit.

