#!/usr/bin/env bash
#
# birch - a simple irc client in bash

esc() {
    case $1 in
        cursor_show):  "\\e[?25h"      ;;
        cursor_hide):  "\\e[?25l"      ;;
        cursor_save):  "\\e7"          ;;
        cursor_load):  "\\e8"          ;;
        cursor_move):  "\\e[$2;$3H"    ;;
        cursor_fake):  "\\e[47m \\e[m" ;;
        clear_screen): "\\e[2J"        ;;
        clear_line):   "\\e[K"         ;;
        scroll_area):  "\\e[$2;$3r"    ;;

        *) return
    esac

    printf %b "$_"
}

clean() {
    term_reset
    kill 0
}

term_setup() {
    esc cursor_hide
    esc clear_screen
    esc scroll_area 1 "$((LINES - 1))"

    stty -echo
}

term_reset() {
    esc clear_screen
    esc scroll_area
    esc cursor_show

    stty echo

    exec 69>&-
}

term_size() {
    resize=

    shopt -s checkwinsize; (:;:)
}

irc_setup() {
    exec 69<>"/dev/tcp/${host:=irc.freenode.net}/6667" || {
        printf '%s\n' "error: Couldn't connect to $host." >&2
        exit 1
    }

    printf 'NICK %s\n' "${nick:=$USER}" >&69
    printf 'USER %s - - :%s\n' "$nick" "$nick" >&69
    printf 'PASS %s\n' "${pass:-}" >&69
    printf 'JOIN %s\n' "${chan:=#kisslinux}" >&69
}

irc_parse() {
    mesg=${1#* :}
    www=${1%%$mesg*}

    read -ra args <<< "${www##:}"
    IFS='!@' read -r unick _ _ <<< "${args[0]}"
}

irc_printf() {
    # shellcheck disable=2059
    printf -v msg_input "$@"

    printf %s "$msg_input"
}

irc_input() {
    esc cursor_save
    esc cursor_move "$LINES"
    esc clear_line

    printf %s "$chan > $msg"

    esc cursor_fake
    esc cursor_load

    IFS= read -rsn 1 -t 0.1 &&
        case $REPLY in
            $'\177'|$'\b')
                msg=${msg%?}
            ;;

            "")
                irc_cmd "$msg"
                msg=
            ;;

            $'\e') ;;

            *)
                msg+=$REPLY
            ;;
        esac
}

irc_cmd() {
    read -ra msg <<< "$1"

    case $1 in
        "") ;;

        /j*)
            printf 'JOIN %s\n' "${msg[1]}" >&69

            chan=$_
            resize=1
        ;;

        /l*)
            printf 'PART %s\n' "${msg[1]:-$chan}" >&69
        ;;

        /m*)
            printf 'PRIVMSG %s :%s\n' "${msg[1]}" "${msg[2]}" >&69
        ;;

        /n*)
            printf 'NICK %s\n' "${msg[1]}" >&69
            nick=$_
        ;;

        /q*)
            printf 'QUIT :%s\n' "${msg[1]}" >&69
            exit
        ;;

        /*)
            printf '%s\n' "error: ${msg[0]} not implemented yet."
        ;;

        *)
            printf 'PRIVMSG %s %s\n' "$chan" ":$1" >&69

            irc_printf '\e[1;3%sm%10s\e[m %s\n' \
                "$((${#nick}/2))" "${nick:0:10}" "$1"
        ;;
    esac
}

irc_output() {
    while read -sru 69 || :; do
        case $REPLY in
            PING*)
                printf 'PONG%s\n' "${REPLY##PING}" >&69
            ;;

            *PRIVMSG*)
                irc_parse "$REPLY"

                irc_printf '\e[1;3%sm%10s\e[m %s\n' \
                    "$((${#unick}/2))" "${unick:0:10}" "$mesg"
            ;;

            *JOIN*|*PART*|*QUIT*)
                REPLY=${REPLY:1}

                case $REPLY in
                    *JOIN*): '-->joined' ;;
                    *PART*): '<--left'   ;;
                    *QUIT*): '<--quit'   ;;
                esac

                irc_printf '%10s %s\n' "${_::3}" \
                    "${REPLY%%\!*} has ${_:3} #${REPLY##*\#}"
            ;;

            *NOTICE*)
                irc_printf '%s\n' "${REPLY##*NOTICE }"
            ;;

            *NICK*)
                irc_parse "$REPLY"

                irc_printf '%10s %s\n' "--" \
                    "$unick is now known as $mesg"
            ;;

            *)
                irc_printf '%s\n' "$REPLY"
            ;;
        esac
    done
}

get_args() {
    while getopts :s:u:p:c:v opt; do
        case $opt in
            s)  host=$OPTARG ;;
            u)  nick=$OPTARG ;;
            p)  pass=$OPTARG ;;
            c)  chan=\#${OPTARG##\#} ;;

            \?) usage ;;

            v)
                printf 'birch 0.0.1\n'
                exit
            ;;

            :)
                printf 'Option -%s requires an argument.\n' "$OPTARG" >&2
                exit 1
            ;;
        esac
    done
}

usage() {
    printf '%s\n' "usage: birch [-s host -u nick -p pass -c channel]"

    exit 1
}


main() {
    get_args "$@"
    term_size
    irc_setup
    term_setup

    trap clean    INT EXIT
    trap resize=1 WINCH

    irc_output &

    for ((;;)) {
        irc_input

        [[ $resize ]] && {
            term_size
            term_setup
        }
    }

    wait
    return 0
}

main "$@"
