.TH BIRCH 1
.SH NAME
birch \- an irc client written in pure bash.
.SH SYNOPSIS
.B birch
\fB\-r\fR

.B birch
\fB\-v\fR

.B birch
[\fBcolors\fR] (See \fBCOLORS\fR below)

.B birch
.IR file ...
.SH DESCRIPTION
.B birch is a minimal irc client written in pure bash.

.SH OPTIONS
.TP
.BR \-s\ host
Server to connect to.
.TP
.BR \-u\ user
Username to use.
.TP
.BR \-p\ password
Password to use.
.TP
.BR \-c\ channel
Channel to join.
.TP
.BR \-h
Show usage and exit.
.TP
.BR \-v
Show version and exit.

